server:
  port: 8888

spring:
  application:
    name: demo-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:\develop\workspace\springcloud-demo\config-files
    bus:
      trace:
        enabled: true

  rabbitmq:
    host: localhost
    port: 5672
    username: docker
    password: ding

logging:
  level:
    org.springframework.cloud.config: DEBUG
